id: P49493EB8
initial_creation_type: input
source_metadata:
  title: Pari Lobzang Rabsal
  language: en
  description: 'Texts by and about Pari Lobzang Rabsal (dpa'' ris blo bzang rab gsal,
    1840–c.1912), the Gelugpa scholar famous for his opposition to Jamgön Mipham''s
    interpretation of Madhyamaka philosophy:'
  volume:
    3a0cd86f75b94617b358dc35a695ea82:
      title: An Appeal for the Prosperity of Teaching and Studying the Five Major
        Scriptures
      parent: Summoning Prosperity
created_at: '2022-03-01T01:10:37.817310'
last_modified_at: '2022-03-01T01:10:37.817317'
